#!/bin/bash

this_proc=$(basename $0)
current_profile_dir=build/profiles
if [ ! -d ${current_profile_dir} ]
then
  current_profile_dir=build/xml
fi
if [ ! -d ${current_profile_dir} ]
then
  echo "${current_profile_dir} not found. Aborting"
  exit 1
fi
profile_dir=$(basename ${current_profile_dir})
ref_dir_def=build.saved/${profile_dir}

usage () {
  echo "Usage : $this_proc [-v] [-d] [--json|--xml]  [-p profile] [ref_profile_dir]"
  echo ""
  echo -e "\tref_profile_dir specified the directory where are stored reference"
  echo -e "\tprofiles (D: build.saved/xml)."
  echo -e ""
  echo -e "\t-d : compare dependency files too"
  echo -e "\t--json: use JSON profiles for comparison (default)"
  echo -e "\t-p profile : compare only the specified profile (without .xml)"
  echo -e "\t-t : terse output (show only the configuration differences"
  echo -e "\t\twithout context, RPM differences ignored)"
  echo -e "\t-v : verbose output (show differences)"
  echo -e "\t-w : ignore all white space"
  echo -e "\t--xml: use XML profiles for comparison (default)"
  echo -e ""
  exit
}

verbose=0
profile='*'
check_dep_files=0
json_profile=1
terse_output=0
diff_options=""
dep_ext=.dep
json_ext=.json
xml_ext=.xml

while [ -n "$(echo $1 | grep '^-')" ]
do
  case "$1" in
    -d|--dep*)
      check_dep_files=1
      ;;

    -h|--help)
      usage
      ;;

    --json)
      json_profile=1
      ;;

    -v|--ver*)
      verbose=1
      ;;

    -w|--ignore-all-space)
      diff_options="-w"
      ;;

    --xml)
      json_profile=0
      ;;

    -p|--pro*)
      shift
      if [ -z "$1" ]
      then
        usage
      fi
      profile=$1
      ;;

    -t|--terse)
      terse_output=1
      ;;

    *)
      echo "Unsupported option : $1"
      usage
      ;;
  esac

  shift
done

if [ -n "$1" ]
then
  ref_dir=$1
else
  ref_dir=$ref_dir_def
fi

if [ $check_dep_files -eq 1 ]
then
  file_pattern="${profile}${dep_ext}"
  echo "Comparing dependency files ($file_pattern)..."

  files=`find $current_profile_dir -name "$file_pattern"`
  for file in $files
  do
      filename=$(basename $file)
      out1="/tmp/${this_proc}.out1"
      sort $file > $out1
      out2="/tmp/${this_proc}.out2"
      sort $ref_dir/$filename > $out2
      xmldiff=`diff $out2 $out1`
      if [ $? -ne 0 ]
      then
        echo Differences found in $file
        if [ $verbose -gt 0 ]
        then
          diff -u $out2 $out1
          echo ""
        fi
      fi
  done
fi

if [ ${json_profile} -eq 1 ]
then
  file_pattern="${profile}${json_ext}"
else
  file_pattern="${profile}${xml_ext}"
fi
echo ""
echo "Comparing profile files ($file_pattern)..."

files=$(find $current_profile_dir -name "$file_pattern" -not -name profiles-info.xml)
for file in $files
do
   #echo $file
    xmldiff=`diff $diff_options $ref_dir $file`
    if [ $? -ne 0 ]
    then
      echo Differences found in $file
      if [ $verbose -gt 0 ]
      then
        diff -u $diff_options $ref_dir $file
        echo ""
       elif [ $terse_output -eq 1 ]
      then
        diff -u $diff_options $ref_dir $file | egrep '^-|\+' | grep -v version | \
                     egrep -v '^(-|\+)</*[0-9a-f_]*>$' | grep -v '^@@.*@@$'
        echo ""
      fi
    fi
done
